name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Check files
        run: |
          echo "Build erfolgreich 🎉"
          ls -la